blank_issues_enabled: false
contact_links:
  - name: UnQStudio related issues
    url: https://github.com/Sandeepgaddam5432/UnQStudio/issues/new/choose
    about: Report issues related to UnQStudio
  - name: Chat
    url: https://example.com/community
    about: Ask questions and discuss with other UnQStudio users.
